AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  DisabledByDefault: true

Security:
  Enabled: true

Bundler:
  Enabled: true

Lint:
  Enabled: true

Naming:
  Enabled: true

Style:
  Enabled: true

Layout:
  Enabled: true

Metrics:
  Enabled: true

Metrics/AbcSize:
  Max: 26

Metrics/CyclomaticComplexity:
  Max: 13

Metrics/PerceivedComplexity:
  Max: 13

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Max: 125
  Enabled: true
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'test/**/*'

Style/ConditionalAssignment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/ExponentialNotation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  AutoCorrect: true

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Lint/MissingSuper:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Style/SingleArgumentDig:
  Enabled: false
