name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.3
            gemfile: Gemfile
          - ruby: 3.2
            gemfile: Gemfile
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v3

      - name: Install poppler-utils
        run: sudo apt-get install -y poppler-utils

      - name: Install antiword
        run: sudo apt-get install -y antiword

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake test
